services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: always
    environment:
      - SECRET_ENCRYPTION_KEY=puNfx1JyTrswzoqEcXY3W5kFlO2M8BDGIZ0PvmjbdtH6RnC97Qhag4LUiAKeVS
    volumes:
      - homarr_data:/appdata
    ports:
      - "7575:7575"

volumes:
  homarr_data:
