services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - FB_DATABASE=/config/filebrowser.db
      - FB_ROOT=/srv
      - FB_LOG=stdout
    volumes:
      - /opt/seedbox:/srv
      - ../../config/fb:/config
    ports:
      - "8081:80"
    restart: always
