services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: always
    environment:
      - SECRET_ENCRYPTION_KEY=b531d7e5ba58a38f2c6f1c91da69873a35696717dfb05058c8f080ab57c27b9d
    volumes:
      - homarr_data:/appdata
    ports:
      - "7575:7575"

volumes:
  homarr_data:
